//! Emit Tier-0 reference vectors from the **Rust** implementation, for the C port to be checked
//! against. `tier0.rs` is dependency-free, so it compiles standalone here:
//!
//! ```sh
//! rustc -O --edition 2021 gen_vectors.rs -o /tmp/gen_vectors && /tmp/gen_vectors > vectors.h
//! ```
//!
//! The C firmware and the nRF54L15 testbed have to agree bit-for-bit on the wire. A divergence
//! produces no error, just a frame that stops matching -- so it must be caught here, mechanically,
//! and not by reading the two implementations side by side.

#[path = "../../lr2021-nrf54l15-rs/src/tier0.rs"]
mod tier0;

use tier0::PrefixFilter;

/// Names chosen to exercise the parts that differ if a port is wrong: the root, single component,
/// the depth cap (9 components, so truncation at MAX_DEPTH=8 is visible), an empty name, and
/// non-ASCII bytes (sign-extension bugs in the FNV loop).
const NAMES: &[&str] = &[
    "/",
    "/A",
    "/A/b",
    "/A/b/c",
    "/ndn/mds/telemetry/o5p-1/imu/seq/42",
    "/a/b/c/d/e/f/g/h/i",
    "",
    "/ndn/\u{00ff}\u{0080}/x",
];

/// Group keys as 16-byte trust contexts. Includes the all-zero "open group" and a key whose bytes
/// exercise the SipHash tail path at every remainder length.
const KEYS: &[[u8; 16]] = &[
    [0u8; 16],
    *b"0123456789abcdef",
    *b"\xff\xfe\xfd\xfc\xfb\xfa\xf9\xf8\xf7\xf6\xf5\xf4\xf3\xf2\xf1\xf0",
];

fn hex16(b: &[u8; 16]) -> String {
    b.iter().map(|x| format!("0x{x:02x},")).collect::<String>()
}

fn main() {
    println!("/* GENERATED by tools/gen_vectors.rs -- do not edit. */");
    println!("/* Reference values from lr2021-nrf54l15-rs/src/tier0.rs (the normative impl). */");
    println!("struct ndr_vec {{ unsigned char key[16]; const char *name;");
    println!("                  unsigned char filter[16]; unsigned char mask[16]; }};");
    println!("static const struct ndr_vec NDR_VECTORS[] = {{");

    for key in KEYS {
        for name in NAMES {
            let mut f = PrefixFilter::new();
            f.insert_name(key, name.as_bytes());
            // The mask a receiver builds for this exact name treated as a registered prefix.
            let m = PrefixFilter::mask_for(key, name.as_bytes());
            let k: String = key.iter().map(|b| format!("0x{b:02x},")).collect();
            println!(
                "  {{ {{{k}}}, \"{name}\", {{{}}}, {{{}}} }},",
                hex16(&f.to_wire()),
                hex16(&m.0)
            );
        }
    }
    println!("}};");
    println!("#define NDR_NVECTORS {}", KEYS.len() * NAMES.len());
    // Pin SipHash itself, not just the filter built on it: the published Aumasson & Bernstein
    // vector for key 000102...0f over the 15-byte message 00..0e.
    let k: [u8; 16] = core::array::from_fn(|i| i as u8);
    let msg: [u8; 15] = core::array::from_fn(|i| i as u8);
    println!("#define NDR_SIPHASH_REF 0x{:016x}ULL", tier0::siphash24(&k, &msg));

    // A self-consistency check on the Rust side too: every name must match the mask of each of its
    // own prefixes. This is the zero-false-negative property the whole design rests on.
    for key in KEYS {
        for name in NAMES {
            let mut f = PrefixFilter::new();
            f.insert_name(key, name.as_bytes());
            tier0::for_each_prefix(name.as_bytes(), |pfx| {
                let m = PrefixFilter::mask_for(key, pfx);
                assert!(
                    f.may_match(&m),
                    "FALSE NEGATIVE: {name:?} vs prefix {:?}",
                    core::str::from_utf8(pfx)
                );
            });
        }
    }
    eprintln!("rust-side zero-false-negative check: OK");
}
